name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with Allure env
        run: npx cypress run --env allure=true

      - name: Generate Allure report
        run: |
          npx allure generate allure-results --clean -o allure-report
          ls -l allure-report

      # Opcional: envie o relatório para o Actions artifact para download posterior
      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
